Update pre-commit

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,12 +1,17 @@
 #!/bin/bash
-# 2013 - fbarbeira
+# 2013 - fbarbeira@dinahosting.com
 #
 #  Pre-commit git hook que comprueba el codigo puppet y erb antes
 # de ser introducido en el repositorio.
 
+# Revisa que sólo se realicen commits en la rama 'develop'.
+if [ `git rev-parse --abbrev-ref HEAD` != "develop" ]; then
+  echo "$(tput setaf 1 ; tput bold ; tput smull)Error$(tput srg0):no estas en la rama 'develop'."
+  exit 1
+fi
 
 # Check sintaxis de ficheros puppet.
-echo -e "\e[01;34m==>\e[00m \e[01;37mRevision de sintaxis de manifests.\e[00m"
+echo "$(tput setaf 4 ; tput bold)==> $(tput setaf 7 ; tput bold)Revision de sintaxis de manifests.$(tput sgr0)"
 for file in `git diff --name-only --cached | grep -E '\.(pp)'`
 do
   if [[ -f $file ]]
@@ -28,13 +33,13 @@ fi
 echo ""
 
 # Check de estilo puppet.
-echo -e "\e[01;34m==>\e[00m \e[01;37mRevision de estilo de manifests.\e[00m"
+echo "$(tput setaf 4 ; tput bold)==> $(tput setaf 7 ; tput bold)Revision de estilo de manifests.$(tput sgr0)"
 for file in `git diff --name-only --cached | grep -E '\.(pp)'`
 do
   if [[ -f $file ]]
   then
     num_files_s+=1
-    puppet-lint --fail-on-warnings $file
+    puppet-lint --fail-on-warnings --no-80chars-check $file
     if [[ $? -ne 0 ]]
     then
       syntax_is_bad=1
@@ -50,7 +55,7 @@ fi
 echo ""
 
 # Check sintaxis de templates.
-echo -e "\e[01;34m==>\e[00m \e[01;37mRevision de sintaxis de templates.\e[00m"
+echo "$(tput setaf 4 ; tput bold)==> $(tput setaf 7 ; tput bold)Revision de sintaxis de templates.$(tput sgr0)"
 for file in `git diff --name-only --cached | grep -E '\.erb'`
 do
   if [[ -f $file ]]
@@ -75,14 +80,14 @@ echo ""
 
 if [[ $syntax_is_bad -eq 1 ]]
 then
-  echo "----------------------------"
-  echo -e "\e[01;31m\e[4mWarning\e[00m\e[24m: Revisa tu codigo de nuevo."
+  echo "---------------------------------------------------------"
+  echo "$(tput setaf 1 ; tput bold)WARNING$(tput sgr0): Revisa tu codigo de nuevo."
   echo "Corrige los errores que se muestran arriba."
   echo "Mientras no sea valido no podras añadirlo al repositorio."
-  echo "----------------------------"
+  echo "---------------------------------------------------------"
   exit 1
 else
   echo "----------------------------"
-  echo -e "\e[00;32mCodigo valido.\e[00m"
+  echo "$(tput setaf 2 ; tput bold)Codigo valido.$(tput sgr0)"
   echo "----------------------------"
 fi
